Controllers/TechController.cs
using HelpDesk.Data;
using HelpDesk.Enums;
using HelpDesk.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HelpDesk.Controllers;
[Authorize("RequireTech")]
public class TechController : Controller
{
    private readonly ApplicationDbContext _dbContext;

    public TechController(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    public async  Task<IActionResult> Index()
    {
        var complaints = await _dbContext.Complaints
            .Include(c => c.User).ToListAsync();
        return View(complaints);
    }

    public async Task<IActionResult> Details(string id)
    {
        try
        {
            var complaint = await _dbContext.Complaints
                .Include(c=>c.User)
                .SingleAsync(c => c.Id.ToString() == id);
            return View(complaint);
        }
        catch (Exception e)
        {
            return NotFound(e.Message);
        }
    }

    public async Task<IActionResult> Update(string id){
        try
        {
            var complaint = await _dbContext.Complaints
                .SingleAsync(c => c.Id.ToString() == id);
            return View(complaint);
        }
        catch (Exception e)
        {
            return NotFound(e.Message);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(Complaint complaint)
    {
        try
        {
            var dbComplaint = await _dbContext.Complaints.SingleAsync(c=>c.Id.ToString() == complaint.Id.ToString());
            if (complaint.Action == null)
            {
                ModelState.AddModelError("action", "Action is required.");   
            }

            if (complaint.Action?.Trim() is { Length: <= 10 })
            {
                ModelState.AddModelError("action", "Action cannot be less than 10 characters.");  
            }
            if (complaint is { Status: Status.Open, IsClosed: true })
            {
                ModelState.AddModelError("status", "Please change Status when closing the complaint."); 
            }
            if (!ModelState.IsValid)
            {
                return View(complaint);
            }

            if(complaint.IsClosed)
            {
                dbComplaint.ClosedAt = DateTime.Now;
            }
            else
            {
                dbComplaint.ClosedAt = null;
            }
            
           
            dbComplaint.Action = complaint.Action;
            dbComplaint.IsClosed = complaint.IsClosed;
            dbComplaint.Status = complaint.Status;
            dbComplaint.UpdatedAt = DateTime.Now;
           


            _dbContext.Update(dbComplaint);
            await _dbContext.SaveChangesAsync();
            return  RedirectToAction("Index");
        }
        catch (Exception e)
        {
            return NotFound(e.Message);
        }
    }
}

Views/Tech/Details.cshtml
@model HelpDesk.Models.Complaint

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Complaint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        
        <dt class = "col-sm-2">
                   Issuer
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.User.Email)
                </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Action)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Action)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Tech" asp-action="Index">Back to List</a>
</div>

Views/Tech/Index.cshtml
@model IEnumerable<Complaint>
@{
    ViewData["Title"] = "Index";
}

<div class="col-6">
    <h1>Complaints</h1>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.Id)
            </th>
            <th>
                Issuer
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Title)
            </th>

            <th>
                @Html.DisplayNameFor(m => m.Status)
            </th>

            <th>Actions</th>

        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.User.Email</td>
                <td>@item.Title</td>
                <td>@item.Status</td>
                <td>
                    <a asp-controller="Tech" asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                    <a asp-controller="Tech" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">Update</a>
                </td>
            </tr>
        }


        </tbody>
    </table>
</div>

Views/Tech/Update.cshtml
@using HelpDesk.Enums
@model Complaint
@{
    ViewData["Title"] = "Update";
}

<h1>Update complaint</h1>
<form method="post">
    <div asp-validation-summary="All"></div>
    @Html.HiddenFor(model => model.Title)
        @Html.HiddenFor(model => model.Description)
    <input type="hidden" asp-for="Id"/>
    <div class="mb-3">
        <label asp-for="Action"></label>
        <input asp-for="Action" class="form-control"/>
        <span asp-validation-for="Action" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Status"></label>
        <select asp-for="Status"
                class="form-select"
                asp-items="Html.GetEnumSelectList<Status>()">
            <option disabled="disabled" selected="selected"> Update status</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>

    </div>
     <div class="mb-3">
            <label>
                <input type="checkbox" asp-for="IsClosed" />
                <span>Close complaint</span>
            </label>
        
        </div>
  
    <button type="submit" class="btn btn-primary">Update</button>
    <a asp-controller="Tech" asp-action="Index" class="btn btn-secondary">Go back</a>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}